[package]
name = "deshia"
version = "0.1.0"
description = "DeshiA — professional image annotation workstation for computer vision research"
authors = ["Md. Mehedi Hasan"]
license = "Apache-2.0"
repository = "https://github.com/0mehedihasan/deshia"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "deshia_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# This feature is used for production builds or when a dev server is not
# specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
